collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3765957
  brandStrength: 0.5382979
  lightness: 0.7808511
  brandColors:
    - '#0D0C0D'
    - '#657630'
    - '#B3B6BD'
    - '#FFFFB4'
    - '#FFFC42'
  rhythmicContrast: 0.3765957
typography_spectrum: 0.1489362
layout_spectrum: 0.4127659
name: 'Water Health Development '
