name: 'Water Health Development '
favicon: null
layout_spectrum: 0.8553191
typography_spectrum: 0.24273
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Connecting water management to public health
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0D0C0D'
    - '#657630'
    - '#B3B6BD'
    - '#FFFFB4'
    - '#FFFC42'
  brandStrength: 0.5382979
  lightness: 0.9375
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
