layout_spectrum: 0.4127659
color:
  saturation: 0.3765957
  brandStrength: 0.2143657
  lightness: 0.7808511
  rhythmicContrast: 0.3765957
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.1489362
name: 'Water Health Development '
