collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2021277
color:
  saturation: 0.287234
  brandStrength: 0.5382979
  lightness: 0.7914894
  brandColors:
    - '#0D0C0D'
    - '#657630'
    - '#B3B6BD'
    - '#FFFFB4'
    - '#FFFC42'
  rhythmicContrast: 0.5638298
layout_spectrum: 0.8553191
name: 'Water Health Development '
